### ISSUE TITLE
Allow Header Customization via Frontend Plugin Framework

### ISSUE THREAD

**Issue by brian-smith-tcril** [openedx/frontend-component-header#521]
It is important for site operators to be able to customize the Header. This is currently supported by having site operators fork this repository and `npm install` from their fork, however, that is a lot to ask of a site operator that just wants to make a few small changes.

Now that [`frontend-plugin-framework`](https://github.com/openedx/frontend-plugin-framework/) exists, we have an opportunity to make the header customization story a better one!

In this issue I would like to discuss:
* What are the ways in which site operators want to customize the header?
  * What Plugin Slots can we create to support those use cases?
* How can we help site operators that currently rely on the forking/`npm install` strategy move to using the frontend plugin framework plugin slot strategy?
  * One way to support this is to have a top-level plugin slot that wraps the entire header. What would the requirements for that top-level plugin slot be?
* What aspects of the current technical architecture of this repository will make this difficult?
  * How do we handle the current `LearningHeader` vs `StudioHeader` vs `DesktopHeader` vs `MobileHeader` situation? Is there a clear path forward for consolidating those? Is consolidating those required to provide a good site operator experience for using plugin slots?
* **Anything and everything else people can think of that will impact how the header plugin slots are created!**

```[tasklist]
## PRs
- [ ] https://github.com/openedx/frontend-component-header/pull/528
- [ ] https://github.com/openedx/frontend-component-header/pull/545
- [ ] https://github.com/openedx/frontend-template-application/pull/832
- [ ] https://github.com/openedx/frontend-app-account/pull/1144
- [ ] https://github.com/openedx/frontend-app-authoring/pull/1424
- [ ] https://github.com/openedx/frontend-app-communications/pull/214
- [ ] https://github.com/openedx/frontend-app-discussions/pull/741
- [ ] https://github.com/openedx/frontend-app-gradebook/pull/409
- [ ] https://github.com/openedx/frontend-app-learner-dashboard/pull/485
- [ ] https://github.com/openedx/frontend-app-learner-record/pull/431
- [ ] https://github.com/openedx/frontend-app-learning/pull/1502
- [ ] https://github.com/openedx/frontend-app-learning/pull/1504
- [ ] https://github.com/openedx/frontend-app-ora-grading/pull/363
- [ ] https://github.com/openedx/frontend-app-payment/pull/887
- [ ] https://github.com/openedx/frontend-app-payment/pull/888
- [ ] https://github.com/openedx/frontend-app-profile/pull/1112
```

**Comment by adamstankiewicz** [comment]
> Anything and everything else people can think of that will impact how the header plugin slots are created!

There might still be an opportunity for `frontend-component-header` to rely on `Navbar` from Paragon ([docs](https://paragon-openedx.netlify.app/components/navbar/)). There's has been [early discussion/design work](https://github.com/openedx/paragon/issues/1451) in the past within Paragon Working Group (`#wg-paragon`) about how to make the Paragon `Navbar` component more generic, with defined slots / permutations, such that it can be used within the platform (e.g., via `frontend-component-header`). The interaction with `Navbar` from Paragon might be out-of-scope for this particular bit, but I still feel this is still a direction possibly worth pursuing.

**Comment by brian-smith-tcril** [comment]
> How do we handle the current LearningHeader vs StudioHeader vs DesktopHeader vs MobileHeader situation?

I think noting how headers are being used in the default enabled MFEs in tutor are using will be helpful for figuring this out:

# Overview (Table)

| MFE | Header |
| - | - |
| [Authn](https://github.com/openedx/frontend-app-authn/) | None |
| [Account](https://github.com/openedx/frontend-app-account/) | [`Header`](https://github.com/openedx/frontend-component-header/blob/master/src/Header.jsx) |
| [Communications](https://github.com/openedx/frontend-app-communications/) | [`LearningHeader`](https://github.com/openedx/frontend-component-header/blob/master/src/learning-header/LearningHeader.jsx) |
| [Course Authoring](https://github.com/openedx/frontend-app-course-authoring/) | [`StudioHeader`](https://github.com/openedx/frontend-component-header/blob/master/src/studio-header/StudioHeader.jsx) |
| [Discussions](https://github.com/openedx/frontend-app-discussions/) | [`LearningHeader`](https://github.com/openedx/frontend-component-header/blob/master/src/learning-header/LearningHeader.jsx) |
| [Gradebook](https://github.com/openedx/frontend-app-gradebook/) | [`Header`](https://github.com/openedx/frontend-component-header/blob/master/src/Header.jsx) |
| [Learner Dashboard](https://github.com/openedx/frontend-app-learner-dashboard/) | [`Header`](https://github.com/openedx/frontend-component-header/blob/master/src/Header.jsx) |
| [Learning](https://github.com/openedx/frontend-app-learning/) | [`LearningHeader`](https://github.com/openedx/frontend-component-header/blob/master/src/learning-header/LearningHeader.jsx) |
| [ORA Grading](https://github.com/openedx/frontend-app-ora-grading/) | [`LearningHeader`](https://github.com/openedx/frontend-component-header/blob/master/src/learning-header/LearningHeader.jsx) |
| [Profile](https://github.com/openedx/frontend-app-profile/) | [`Header`](https://github.com/openedx/frontend-component-header/blob/master/src/Header.jsx) |

# Details

## [Authn](https://github.com/openedx/frontend-app-authn/)
No header
## [Account](https://github.com/openedx/frontend-app-account/)
### [Import](https://github.com/openedx/frontend-app-account/blob/17ce32b80c3d8da5c51ab6db5fc4889c814db786/src/index.jsx#L13)
```jsx
import Header from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-account/blob/17ce32b80c3d8da5c51ab6db5fc4889c814db786/src/index.jsx#L33)
```jsx
<Header />
```
## [Communications](https://github.com/openedx/frontend-app-communications/)
### [Import](https://github.com/openedx/frontend-app-communications/blob/1e1f269b6b638e5cae1ff3c1c951192a6bddb146/src/components/page-container/PageContainer.jsx#L5)
```jsx
import { LearningHeader as Header } from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-communications/blob/1e1f269b6b638e5cae1ff3c1c951192a6bddb146/src/components/page-container/PageContainer.jsx#L64-L69)
```jsx
<Header
  className="learning-header"
  courseOrg={courseMetadata.org}
  courseNumber={courseMetadata.number}
  courseTitle={courseMetadata.title}
/>
```
## [Course Authoring](https://github.com/openedx/frontend-app-course-authoring/)
### [Import](https://github.com/openedx/frontend-app-course-authoring/blob/bb88101255ce1515045be54102afd7466ef24c93/src/header/Header.tsx#L5)
```jsx
import { StudioHeader } from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-course-authoring/blob/bb88101255ce1515045be54102afd7466ef24c93/src/header/Header.tsx#L60-L68)
```jsx
<StudioHeader
  org={org}
  number={number}
  title={title}
  isHiddenMainMenu={isHiddenMainMenu}
  mainMenuDropdowns={mainMenuDropdowns}
  outlineLink={outlineLink}
  searchButtonAction={meiliSearchEnabled ? openSearchModal : undefined}
/>
```
## [Discussions](https://github.com/openedx/frontend-app-discussions/)
### [Import](https://github.com/openedx/frontend-app-discussions/blob/3391e966f3306cd31ff25736d045b6b9a5e98321/src/discussions/discussions-home/DiscussionsHome.jsx#L11)
```jsx
import { LearningHeader as Header } from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-discussions/blob/3391e966f3306cd31ff25736d045b6b9a5e98321/src/discussions/discussions-home/DiscussionsHome.jsx#L84)
```jsx
{!enableInContextSidebar && (<Header courseOrg={org} courseNumber={courseNumber} courseTitle={courseTitle} />)}
```
## [Gradebook](https://github.com/openedx/frontend-app-gradebook/)
### [Import](https://github.com/openedx/frontend-app-gradebook/blob/ccb786510059b063f7928a9a634f7d2c3dfccbae/src/App.jsx#L7)
```jsx
import Header from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-gradebook/blob/ccb786510059b063f7928a9a634f7d2c3dfccbae/src/App.jsx#L18)
```jsx
<Header />
```
## [Learner Dashboard](https://github.com/openedx/frontend-app-learner-dashboard/)
> [!IMPORTANT]
> Assuming https://github.com/openedx/frontend-app-learner-dashboard/pull/327 lands
### [Import](https://github.com/openedx/frontend-app-learner-dashboard/blob/d7bec0724c55762c3cf6188b311461719560b4a4/src/containers/LearnerDashboardHeader/index.jsx#L5)
```jsx
import Header from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-learner-dashboard/blob/d7bec0724c55762c3cf6188b311461719560b4a4/src/containers/LearnerDashboardHeader/index.jsx#L32-L36)
```jsx
<Header
  mainMenuItems={learnerHomeHeaderMenu.mainMenu}
  secondaryMenuItems={learnerHomeHeaderMenu.secondaryMenu}
  userMenuItems={learnerHomeHeaderMenu.userMenu}
/>
```
## [Learning](https://github.com/openedx/frontend-app-learning/)
### [Import (CourseAccessErrorPage)](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/generic/CourseAccessErrorPage.jsx#L2)
```jsx
import { LearningHeader as Header } from '@edx/frontend-component-header';
```
### [Use (CourseAccessErrorPage)](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/generic/CourseAccessErrorPage.jsx#L31)
```jsx
<Header />
```
### [Import (TabPage)](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/tab-page/TabPage.jsx#L8)
```jsx
import { LearningHeader as Header } from '@edx/frontend-component-header';
```
### [Use (TabPage)](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/tab-page/TabPage.jsx#L67)
```jsx
<Header courseOrg={org} courseNumber={number} courseTitle={title} />
```
### [Import (GoalUnsubscribe)](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/course-home/goal-unsubscribe/GoalUnsubscribe.jsx#L6)
```jsx
import { LearningHeader as Header } from '@edx/frontend-component-header';
```
### [Use (GoalUnsubscribe)](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/course-home/goal-unsubscribe/GoalUnsubscribe.jsx#L41)
```jsx
<Header showUserDropdown={false} />
```
## [ORA Grading](https://github.com/openedx/frontend-app-ora-grading/)
### [Import](https://github.com/openedx/frontend-app-ora-grading/blob/f433d33f9d4101b8535ddd4f6221474d69bf272a/src/App.jsx#L7)
```jsx
import { LearningHeader as Header } from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-ora-grading/blob/f433d33f9d4101b8535ddd4f6221474d69bf272a/src/App.jsx#L23-L28)
```jsx
<Header
  courseTitle={courseMetadata.title}
  courseNumber={courseMetadata.number}
  courseOrg={courseMetadata.org}
  data-testid="header"
/>
```
## [Profile](https://github.com/openedx/frontend-app-profile/)
### [Import](https://github.com/openedx/frontend-app-profile/blob/a7ed0cd62ac30c75d17eefac875fc22f233444f1/src/index.jsx#L19)
```jsx
import Header from '@edx/frontend-component-header';
```
### [Use](https://github.com/openedx/frontend-app-profile/blob/a7ed0cd62ac30c75d17eefac875fc22f233444f1/src/index.jsx#L34)
```jsx
<Header />
```

**Comment by brian-smith-tcril** [comment]
### Adding screenshots to aid in visual discussions

## [Authn](https://github.com/openedx/frontend-app-authn/)
No header
## [Account](https://github.com/openedx/frontend-app-account/)
![Screenshot from 2024-08-12 11-23-24](https://github.com/user-attachments/assets/8a0c23ef-b35b-4aa7-983f-6f1950aab10f)
![image](https://github.com/user-attachments/assets/b29b17e0-28c8-48ed-9589-b1697f6b295a)
![image](https://github.com/user-attachments/assets/12889b11-a6c3-4a7e-a9fc-de5ddc2b4c1d)

## [Communications](https://github.com/openedx/frontend-app-communications/)
![image](https://github.com/user-attachments/assets/da8b1732-9704-4c3a-a11c-0dbe40582e9d)
![image](https://github.com/user-attachments/assets/c4eb4108-2448-4fa1-bf5e-b86c2dd54238)

## [Course Authoring](https://github.com/openedx/frontend-app-course-authoring/)
![image](https://github.com/user-attachments/assets/bf3f2e42-3a5f-4404-ab0c-be1bb9106cec)
![image](https://github.com/user-attachments/assets/4fd67eb3-05ed-4438-85d7-9dcf298381b5)
![image](https://github.com/user-attachments/assets/7cbd5ca2-8a21-46f6-a633-db06de3df08b)
![image](https://github.com/user-attachments/assets/2474d620-ecd2-46c9-8990-c104c9988aa7)
![image](https://github.com/user-attachments/assets/e96cf35f-150e-4b2e-a93a-cadc0dedefe4)
![image](https://github.com/user-attachments/assets/08db4d6e-52a7-413a-bcf0-43aa8d4725aa)

## [Discussions](https://github.com/openedx/frontend-app-discussions/)
![image](https://github.com/user-attachments/assets/91373703-1d8a-4108-a210-e172e472f7d0)
![image](https://github.com/user-attachments/assets/a14d6e61-7098-4a85-932c-429bd9b32035)

## [Gradebook](https://github.com/openedx/frontend-app-gradebook/)
![image](https://github.com/user-attachments/assets/86efe598-eea9-4c2c-ae8e-71a7ee14310b)
![image](https://github.com/user-attachments/assets/52b4d53f-778b-4ad0-847b-ab79c003d3b6)
![image](https://github.com/user-attachments/assets/84b8aff2-400c-4238-a737-a361dfd8423f)

## [Learner Dashboard](https://github.com/openedx/frontend-app-learner-dashboard/)
> [!IMPORTANT]
> These screenshots are from before https://github.com/openedx/frontend-app-learner-dashboard/pull/327 landed

![image](https://github.com/user-attachments/assets/49723c36-cf08-4358-9aa7-ea44bc6737fe)
![image](https://github.com/user-attachments/assets/99c685f7-d55d-46da-8e01-e5a9e187dda9)
![image](https://github.com/user-attachments/assets/51db7c6c-75c3-4949-87ba-af6ccdc4db8c)

# //todo

## [Learning](https://github.com/openedx/frontend-app-learning/)
### [CourseAccessErrorPage](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/generic/CourseAccessErrorPage.jsx#L2)

### [TabPage](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/tab-page/TabPage.jsx#L8)

### [GoalUnsubscribe](https://github.com/openedx/frontend-app-learning/blob/99a44dda3773424c221cca04e7a68046dbbbe5a7/src/course-home/goal-unsubscribe/GoalUnsubscribe.jsx#L6)

## [ORA Grading](https://github.com/openedx/frontend-app-ora-grading/)

## [Profile](https://github.com/openedx/frontend-app-profile/)

**Comment by michaelwheeler** [comment]
> What are the ways in which site operators want to customize the header?

It would be really great to simply be able to add/remove/modify links in the main navigation and user menus without having to maintain an entire header component.

**Comment by brian-smith-tcril** [comment]
@asadali145 I'd love to hear your thoughts on this! In https://github.com/openedx/platform-roadmap/issues/349 you noted wanting to be able to customize the URLs for the links in the user dropdown menu - are there any other header customizations you were hoping to be able to do without forking?

**Comment by jmakowski1123** [comment]
Product Requirements defined here - please provide input in the wiki! https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4412243977/Proposal+Customizable+Header+for+LMS

**Comment by asadali145** [comment]
@brian-smith-tcril This issue sums up things nicely and identifies all our pain points.

@jmakowski1123 has added all of the customizations that we look for in https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4412243977/Proposal+Customizable+Header+for+LMS. I have left a comment with a couple more improvements https://openedx.atlassian.net/wiki/spaces/OEPM/pages/4412243977/Proposal+Customizable+Header+for+LMS?focusedCommentId=4413292607.

**Comment by brian-smith-tcril** [comment]
Thanks for reminding me about username replacement @asadali145!

As to the "is there a way to do this or is it still in progress" question, my answer is "both."

It is currently possible only via fully replacing the header (using a `header_slot` https://github.com/openedx/frontend-app-learning/tree/master/src/plugin-slots/HeaderSlot). I agree there should be a simpler way to do this, so I plan to add new slots wrapping the *content within* the button itself in each of the places it appears (mobile/desktop/learning headers).

I should be able to get PRs adding those new slots out to `frontend-component-header` sometime next week, at which point PRs will need to be made updating the version of `frontend-component-header` used in each MFE.

**Comment by brian-smith-tcril** [comment]
I'm going to go ahead and close this mega-issue out. If there are specific things that aren't currently possible with the existing slots we can make new issues to track those.
